### ISSUE TITLE
Create graphics for MVP Wagtail page

### ISSUE THREAD

**Issue by natalieworth** [MozillaFoundation/Design#813] opened 2021-03-30 20:30 UTC
Create 16:9 or 16:6 images based on the graph and creative direction established for the Net Neutrality campaign.

cc @nancyt1

**Comment by nancyt1** [comment] 2021-04-09 19:59
Closing because it looks like a duplicate of [this ticket ](https://github.com/MozillaFoundation/Design/issues/812)

**Closed by nancyt1** 2021-04-09 19:59 UTC
Labels: design
